# Generated by Django 5.0.6 on 2024-07-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Group'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': "User's message", 'verbose_name_plural': "User's message"},
        ),
    ]
