# Generated by Django 5.0.6 on 2024-07-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_groups_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': "User's message", 'verbose_name_plural': "User's messages"},
        ),
    ]
