# Generated by Django 5.0.6 on 2024-07-12 13:03

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media', verbose_name='media')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
