# Generated by Django 5.0.6 on 2024-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'image'), ('music', 'video'), ('audio', 'audio'), ('file', 'file'), ('video', 'video')], max_length=30, verbose_name='type')),
                ('file', models.FileField(upload_to='media/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
    ]
