# Generated by Django 5.0.6 on 2024-07-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Advertising', 'verbose_name_plural': 'Advertisings'},
        ),
    ]
