# Generated by Django 5.0.6 on 2024-07-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
