# Generated by Django 5.0.6 on 2024-07-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
