# Generated by Django 5.0.6 on 2024-07-15 13:24

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactus_alter_contacts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'PrivacyPolicy',
                'verbose_name_plural': 'PrivacyPolicy',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='msg',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
