# Generated by Django 5.0.6 on 2024-07-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactwithusmobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmistake',
            options={'verbose_name': 'About Mistake', 'verbose_name_plural': 'About Mistakes'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
    ]
