# Generated by Django 5.0.6 on 2024-07-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_advertising_created_at_alter_advertising_image_and_more'),
        ('company', '0004_appinfo_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(verbose_name='Telegram URL')),
                ('likedin', models.URLField(verbose_name='LinkedIN URL')),
                ('facebook', models.URLField(verbose_name='Facebook URL')),
                ('instagram', models.URLField(verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsor',
            },
        ),
    ]
