# Generated by Django 5.0.6 on 2024-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_socialmedia_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About Mistake',
                'verbose_name_plural': 'About Mistake',
            },
        ),
    ]
