# Generated by Django 5.0.6 on 2024-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_aboutmistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmistake',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
