# Generated by Django 5.0.6 on 2024-07-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_aboutmistake_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='latitude',
            field=models.FloatField(default=4314.541, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='longitude',
            field=models.FloatField(default=45215.65437, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
