# Generated by Django 5.0.6 on 2024-07-17 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_contacts_latitude_contacts_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
