# Generated by Django 5.0.6 on 2024-07-26 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('click_count', models.PositiveIntegerField(verbose_name='Click Count')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.CharField(choices=[('local', 'Local'), ('global', 'Global')], max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('users', models.ManyToManyField(related_name='clubusers', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.URLField(verbose_name='Location link')),
                ('date', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.club', verbose_name='Club')),
            ],
        ),
        migrations.CreateModel(
            name='StepTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_for_each_test', models.FloatField(verbose_name='Ball for each question')),
                ('question_count', models.PositiveIntegerField(verbose_name='Question Count')),
                ('question_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], max_length=30, verbose_name='Question type')),
                ('test_type', models.CharField(max_length=30, verbose_name='Test type')),
                ('time_for_test', models.DurationField(verbose_name='Test time limit')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.step', verbose_name='Step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='SubjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_test_ball', models.PositiveIntegerField(verbose_name='Total test ball')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.category', verbose_name='Category')),
            ],
        ),
    ]
