# Generated by Django 5.0.6 on 2024-07-27 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Club'},
        ),
        migrations.AlterModelOptions(
            name='clubmeeting',
            options={'verbose_name': 'Club Meeting', 'verbose_name_plural': 'Club Meeting'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Step', 'verbose_name_plural': 'Step'},
        ),
        migrations.AlterModelOptions(
            name='steptest',
            options={'verbose_name': "Step's test", 'verbose_name_plural': "Step's test"},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subject'},
        ),
        migrations.AlterModelOptions(
            name='subjecttitle',
            options={'verbose_name': 'Subject title', 'verbose_name_plural': 'Subject title'},
        ),
        migrations.AlterModelOptions(
            name='usersubject',
            options={'verbose_name': "User's subject", 'verbose_name_plural': "User's subject"},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancy'},
        ),
        migrations.RemoveField(
            model_name='steptest',
            name='question_type',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.subjecttitle', verbose_name='Subject title'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StepLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Step lesson')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='File')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.step', verbose_name='Step')),
            ],
            options={
                'verbose_name': "Step's lesson",
                'verbose_name_plural': "Step's lesson",
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], max_length=30, verbose_name='Question type')),
                ('question', models.TextField(verbose_name='Question')),
                ('steptest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.steptest', verbose_name='Step test')),
            ],
            options={
                'verbose_name': "Test's question",
                'verbose_name_plural': "Test's question",
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_correct', models.BooleanField(verbose_name='Is correct')),
                ('test_quetion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.testquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': "Test's answer",
                'verbose_name_plural': "Test's answer",
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.testanswer', verbose_name='Answer')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.testquestion', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Test result',
                'verbose_name_plural': 'Test result',
            },
        ),
        migrations.CreateModel(
            name='UserTotelTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.FloatField(verbose_name='Ball')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Count of correct answers')),
                ('step_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.steptest', verbose_name='Step test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('user_test_results', models.ManyToManyField(related_name='testresults', to='subject.usertestresult', verbose_name='Test Results')),
            ],
            options={
                'verbose_name': 'Total test result',
                'verbose_name_plural': 'Total test result',
            },
        ),
    ]
