# Generated by Django 5.0.6 on 2024-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_category_options_alter_club_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptest',
            name='ball_for_each_test',
            field=models.FloatField(verbose_name='Bal for each question'),
        ),
        migrations.AlterField(
            model_name='usersubject',
            name='total_test_ball',
            field=models.PositiveIntegerField(verbose_name='Total test bal'),
        ),
        migrations.AlterField(
            model_name='usertoteltestresult',
            name='ball',
            field=models.FloatField(verbose_name='Bal'),
        ),
    ]
