name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: root@45.138.158.251
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@45.138.158.251 'bash -s' < deploy.sh
